---

## DB datasource configuration for postgresql ##
spring.datasource.url: jdbc:postgresql://app-discovery-db/appdiscovery
spring.datasource.username: appdiscovery
spring.datasource.password: secret
spring.datasource.driver-class-name: org.postgresql.Driver
spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql: false
spring.jpa.hibernate.ddl-auto: create
